### ISSUE TITLE
Add attribution of source

### ISSUE THREAD

**Issue by alexgloverl** [shobrook/statcode#7]
This is really, really cool; it's the last time that I ever google a status code. :)

However, it appears that the descriptions that you use in [`code_descriptions.yml`](https://github.com/shobrook/statcode/blob/master/statcode/code_descriptions.yml) are taken from the [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) — I can't find a prior source from which both you and the MDN would have taken the descriptions.

(If it's not the case, then please ignore the rest of this issue, though depending on the license of the original source you may need to add attribution to there.)

MDN's documentation is under a CC BY-SA license, (see [here](https://developer.mozilla.org/en-US/docs/MDN/About#Copyrights_and_licenses)) which means that you need to provide attribution. I think that adding a comment to the start of `code_descriptions.yml` to the effect of:

```python
# Taken from https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
# Redistributed and modified under CC BY-SA
```

and possibly adding a `COPYRIGHT` section to the `statcode` output itself (I'm basing myself on the `ls` manpage (`man ls`)):

```
COPYRIGHT
    Copyright  © CC BY-SA Mozilla Contributors <https://developer.mozilla.org/en-US/docs/Web/HTTP/Status>
```

possibly adding yourself to the copyright list.

Apart from the legal/ethical aspect, the practical advantage of adding attribution is that the user can see  where the information came from, if it's changed, if there are any further linked resources in the original source, etc.

(Also, sorry for being *that* guy and thanks again for a cool piece of software!)

**Comment by Malex** [comment]
Should be closed, see last merged pr
